### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [addingwell/r-advertising-tag#1]
https://github.com/addingwell/r-advertising-tag/blob/fe603588597068becd4cc66f3f7db406b8117445/template.tpl#L196-L197

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by WFrancois** [comment]
Hey!

Thanks for the report, this is fixed in the latest release
